#!/usr/bin/env bash

set -e

# Update all submodules
git submodule update --init --recursive

ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/dircolors" "$HOME/.dircolors"
ln -sf "$PWD/inputrc" "$HOME/.inputrc"
ln -sf "$PWD/profile" "$HOME/.profile"
ln -sf "$PWD/profile" "$HOME/.bash_profile"
ln -sf "$PWD/zshrc" "$HOME/.zshrc"
ln -sf "$PWD/zshenv" "$HOME/.zshenv"
if [[ `uname` = CYGWIN* ]]; then
  ln -sf "$PWD/minttyrc" "$HOME/.minttyrc"
fi

for i in vim tmux; do
  cd $i && ./setup
  cd -
done

./bin/bootstrap_shell.sh
