#!/bin/sh
#
# Vim

set -e

if ! command -v node >/dev/null 2>&1; then
  echo '  installing node for CoC'
  if [ "$(uname -s)" == "Darwin" ]; then
    if ! [ "$DOT_TYPE" == "full" ]; then
      command -v node >/dev/null 2>&1 || { echo '  Please install node manually before continuing'; exit 1; }
    fi
    eval $package_manager node
  else
    sudo apt install -y npm
    sudo npm install -y -g npm
  fi
fi
echo '  installing CoC extensions'
if [ "$DOT_TYPE" == "full" ]; then
  coc_extensions='coc-json coc-html coc-go coc-jedi coc-java'
else
  coc_extensions='coc-json coc-html'
fi
echo "WARNING +CocInstall is not working from shell, I get an error 'E605: Exception not caught: Error on "installExtensions" request: ...'. Run it manually instead."
# vim -esN +"CocInstall -sync $coc_extensions | q" +qall
vim -N +CocUpdateSync +qall
echo '  installing helptags'
for plugin in $(find -H "$HOME/.vim/pack/plugin/start/" -maxdepth 2 -name 'doc'); do
  vim -esN +"helptags $plugin" +qall
done
