#!/bin/sh
#
# Vim

set -e

if ! command -v node >/dev/null 2>&1; then
  echo '  installing node for CoC'
  if [ "$(uname -s)" == "Darwin" ]; then
    if [ "$DOT_TYPE" == "minimal" ]; then
      echo '  Please install node manually before continuing'
      exit 0
    fi
    eval $package_manager node
  else
    sudo apt install npm
    sudo npm install -g npm
  fi
fi
echo '  installing CoC extensions'
coc_extensions='coc-json coc-html coc-go coc-jedi coc-java'
vim -esN +"CocInstall -sync $coc_extensions | q" +qall
echo '  installing helptags'
for plugin in $(find -H "$HOME/.vim/pack/plugin/start/" -maxdepth 2 -name 'doc'); do
  vim -esN +"helptags $plugin" +qall
done
