#!/bin/sh
#
# Vim

set -e


link_file () {
  local src=$1 dst=$2
  rm -rf "$dst" 2>/dev/null
  ln -s "$src" "$dst"
}

mkdir -p "$HOME/Library/Services"

# Remap keys as per https://rakhesh.com/mac/using-hidutil-to-map-macos-keyboard-keys/
# This adds a launch agent which runs at login time, updating the following key mappings:
# - Turn off caps lock
link_file "$DOT/macos/local.keymap.plist" "$HOME/Library/LaunchAgents/local.keymap.plist"
# This adds the MacOS automator services that open specific apps, we bind these to keyboard
# shortcuts in "$DOT/macos/setdefaults"
for file in $DOT/macos/*.workflow; do
  link_file "$file" "$HOME/Library/Services/$(basename $file)"
done


# Only install software if DOT_TYPE==full
[ "$DOT_TYPE" == "full" ] || exit 0

# Check for Homebrew
if test ! $(which brew)
then
  echo '  installing Homebrew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "  updating Homebrew"
brew update >/dev/null

if ! [ -e "/Applications/LastPass.app" ]; then
  echo '  installing lastpass'
  eval $package_manager lastpass
  echo '  TODO - go manually enable the extension in safari'
fi
