#!/bin/sh
#
# Vim

set -e


# Remap keys as per https://rakhesh.com/mac/using-hidutil-to-map-macos-keyboard-keys/
# - Turn off caps lock
link_remap () {
  src="$DOT/macos/local.keymap.plist"
  dst_file="$HOME/Library/LaunchAgents/local.keymap.plist"
  rm -rf "$dst_file"
  ln -s "$src" "$dst_file"
}

link_remap

# Only install software if DOT_TYPE==full
[ "$DOT_TYPE" == "full" ] || exit 0

# Check for Homebrew
if test ! $(which brew)
then
  echo '  installing Homebrew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "  updating Homebrew"
brew update >/dev/null

if ! [ -e "/Applications/LastPass.app" ]; then
  echo '  installing lastpass'
  eval $package_manager lastpass
  echo '  TODO - go manually enable the extension in safari'
fi
