#!/bin/sh
#
# Vim

set -e

# Check for Homebrew
if test ! $(which brew)
then
  echo '  installing Homebrew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "  updating Homebrew"
brew update >/dev/null

if ! [ -e "/Applications/LastPass.app" ]; then
  echo '  installing lastpass'
  eval $package_manager lastpass
  echo '  TODO - go manually enable the extension in safari'
fi
