#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

info 'updating submodules'
git submodule update --remote --merge


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
