#!/bin/bash

if [ "$DOT_TYPE" == "full" ]; then
  declare -a tools=('tldr' 'glow' 'fzf' 'ripgrep' 'alacritty')
  declare -a cmds=('tldr' 'glow' 'fzf' 'rg' 'alacritty')
else
  command -v fzf >/dev/null 2>&1 || { echo '  Please install fzf manually before continuing'; exit 1; }
  command -v rg >/dev/null 2>&1 || { echo '  Please install rg manually before continuing'; exit 1; }
fi

arraylength=${#tools[@]}
for (( i = 0; i < $arraylength; i++ )) do
  tool="${tools[i]}"
  cmd="${cmds[i]}"
  command -v "$cmd" >/dev/null 2>&1 || { echo "  installing $tool"; eval $package_manager "$tool"; }
done
